from odoo import fields, models


class KioskSession(models.Model):
    """Kiosk login session for QR code authentication.

    Flow:
    1. rbackend generates kiosk_token locally and syncs to Odoo
    2. QR code points to nn_booking login page with kiosk_token
    3. User logs in, nn_booking writes partner_id to this record
    4. rbackend syncs and sees authenticated session
    """
    _name = "nn.kiosk.session"
    _description = "Kiosk Login Session"
    _rec_name = "kiosk_token"
    _order = "create_date desc"

    kiosk_token = fields.Char(
        string="Kiosk Token",
        required=True,
        index=True,
        help="Unique token generated by reception backend",
    )
    partner_id = fields.Many2one(
        "res.partner",
        string="Partner",
        ondelete="set null",
        index=True,
        help="Authenticated partner (set after login)",
    )
    status = fields.Selection(
        selection=[
            ("pending", "Pending"),
            ("authenticated", "Authenticated"),
            ("expired", "Expired"),
        ],
        string="Status",
        default="pending",
        required=True,
        index=True,
    )
    location_code = fields.Char(
        string="Location Code",
        index=True,
        help="Identifies which rbackend/location created this session",
    )
    expires_at = fields.Datetime(
        string="Expires At",
        help="When this session expires if not authenticated",
    )
    authenticated_at = fields.Datetime(
        string="Authenticated At",
        help="When the user completed login",
    )

    _sql_constraints = [
        ("kiosk_token_uniq", "unique(kiosk_token)", "Kiosk token must be unique"),
    ]

    def action_authenticate(self, partner_id):
        """Called by nn_booking after successful login."""
        self.ensure_one()
        self.write({
            "partner_id": partner_id,
            "status": "authenticated",
            "authenticated_at": fields.Datetime.now(),
        })
        return True

    def action_expire(self):
        """Mark session as expired."""
        self.write({"status": "expired"})
        return True
